---
application:
  name: "score-api"
  project: "score"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 3000
routers:
- name: "main-score-api"
  routes:
  - application_name: "score-api"
    paths:
    - "/*"
